name 'hachi_resource_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hachi_resource_server'
long_description 'Installs/Configures hachi_resource_server'
version '0.1.0'
