source 'https://rubygems.org'

gem 'chef'
gem 'berkshelf', ">=4.0.0"
gem 'rake'
gem 'json'
gem 'knife-google', '>= 1.3.2', :github => 'chef/knife-google'
gem 'colorize'
gem 'pry'
gem 'foodcritic'
gem 'chefspec'
gem 'serverspec'
gem 'test-kitchen'
gem 'kitchen-vagrant'
