Vagrant.configure(2) do |config|
  config.berkshelf.enabled = true
  config.vm.box = "opscode-ubuntu-14.04"
  config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell" do |s|
    s.inline = "dpkg -i /vagrant/chef_12.6.0-1_amd64.deb"
  end
  config.vm.provision "chef_solo" do |chef|
    chef.install = false
    #chef.log_level = "debug"
    chef.add_recipe "hachi-cookbook"
  end
end
