defaults: &DEFAULTS
  ldap_host: localhost
  ldap_port: '389'
  ldap_admin_username: 'cn=admin,dc=go-jek,dc=com'
  ldap_admin_password: '!Abcd1234'
  ldap_treebase: 'dc=go-jek,dc=com'
  ldap_dc: 'go-jek.com'

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
